import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    app: "src/app.ts",
    "cli/env": "src/cli/env.ts",
    "cli/init": "src/cli/init.ts",
    "cli/run": "src/cli/run.ts",
    "cli/chat": "src/cli/chat.ts",
    "cli/check": "src/cli/check.ts",
    "cli/upgrade": "src/cli/upgrade.ts",
    "cli/snapshot-warmup": "src/cli/snapshot-warmup.ts",
    instrumentation: "src/instrumentation.ts",
    nitro: "src/nitro.ts",
    reporting: "src/reporting.ts",
    vercel: "src/vercel.ts",
  },
  format: "esm",
  tsconfig: "tsconfig.build.json",
  dts: false,
  outDir: "dist",
  clean: true,
  splitting: true,
  external: [
    "#junior/config",
    "hono",
    "@sentry/node",
    // All runtime npm dependencies stay external
    "@ai-sdk/gateway",
    "@chat-adapter/slack",
    "@chat-adapter/state-memory",
    "@chat-adapter/state-redis",
    "@earendil-works/pi-agent-core",
    "@earendil-works/pi-ai",
    "@sinclair/typebox",
    "@slack/web-api",
    "@vercel/functions",
    "@vercel/queue",
    "@vercel/sandbox",
    "ai",
    "bash-tool",
    "chat",
    "just-bash",
    "node-html-markdown",
    "yaml",
    "zod",
  ],
});
