import { useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { codeToHtml, type BundledLanguage, type DecorationItem } from "shiki/bundle/web";

import { canRenderStructuredMarkup, parseMarkupNodes } from "./format";
import type { CodeBlock, MarkupNode } from "./types";
import {
  buildSearchDecorations,
  useTranscriptSearch,
} from "./components/transcriptSearch";

declare const shikiHtmlBrand: unique symbol;

/** HTML generated by Shiki and safe to pass to the highlighted code shell. */
export type ShikiHtml = string & { readonly [shikiHtmlBrand]: true };

/** Count rendered children so transcripts can decide which markup node expands. */
export function countStructuredBlockChildren(block: CodeBlock): number {
  if (!canRenderStructuredMarkup(block)) return 1;
  const rootCount = parseMarkupNodes(block.code, block.language).length;
  return rootCount > 0 ? rootCount : 1;
}

/** Render structured markup blocks as collapsible nodes instead of flat code. */
export function StructuredMarkup(props: {
  block: CodeBlock;
  firstChildIndex: number;
  lastChildIndex: number;
}) {
  const nodes = parseMarkupNodes(props.block.code, props.block.language);
  if (nodes.length === 0) {
    return (
      <HighlightedCode
        code={props.block.code}
        language={props.block.language}
      />
    );
  }

  return (
    <>
      {nodes.map((node, index) => (
        <div
          className="grid min-w-0 gap-0 py-0.5 pl-4 font-mono text-[0.86rem] leading-relaxed text-[#b8b8b8]"
          key={index}
        >
          <MarkupNodeView
            defaultOpen={props.firstChildIndex + index === props.lastChildIndex}
            node={node}
          />
        </div>
      ))}
    </>
  );
}

function MarkupNodeView(props: { defaultOpen?: boolean; node: MarkupNode }) {
  if (props.node.type === "text") {
    return (
      <div className="min-w-0 whitespace-pre-wrap break-words text-white">
        {props.node.text.trim()}
      </div>
    );
  }

  return (
    <MarkupElementView defaultOpen={props.defaultOpen} node={props.node} />
  );
}

function MarkupElementView(props: {
  defaultOpen?: boolean;
  node: Extract<MarkupNode, { type: "element" }>;
}) {
  const children = props.node.children;
  const hasChildren = children.length > 0;
  const [open, setOpen] = useState(props.defaultOpen ?? true);
  const attributes = props.node.attributes.map(([name, value]) => (
    <span className="ml-1.5 text-[#b8b8b8]" key={name}>
      {name}=<span className="text-white">"{value}"</span>
    </span>
  ));

  if (!hasChildren) {
    return (
      <div className="-ml-1 flex min-w-0 flex-wrap items-baseline px-1 py-0.5">
        <span className="text-[#888]">&lt;</span>
        <span className="font-bold text-white">{props.node.tagName}</span>
        {attributes}
        <span className="text-[#888]"> /&gt;</span>
      </div>
    );
  }

  return (
    <details
      className="min-w-0 break-words"
      onToggle={(event) => {
        if (event.currentTarget !== event.target) return;
        setOpen(event.currentTarget.open);
      }}
      open={open}
    >
      <summary className="-ml-1 flex w-full max-w-full cursor-pointer list-none flex-wrap items-baseline px-1 py-0.5 transition-colors hover:bg-white/[0.05] hover:text-white [&::-webkit-details-marker]:hidden">
        <span className="mr-1 w-2 text-white">{open ? "-" : "+"}</span>
        <span className="text-[#888]">&lt;</span>
        <span className="font-bold text-white">{props.node.tagName}</span>
        {attributes}
        <span className="text-[#888]">&gt;</span>
      </summary>
      <div className="ml-1 grid gap-0 border-l border-white/10 pl-3">
        {children.map((child, index) => (
          <MarkupNodeView
            defaultOpen={index === children.length - 1}
            key={index}
            node={child}
          />
        ))}
      </div>
      <div
        className="-ml-1 flex min-w-0 flex-wrap items-baseline px-1 py-0.5 transition-colors hover:bg-white/[0.05]"
        role="button"
        tabIndex={0}
      >
        <span className="text-[#888]">&lt;/</span>
        <span className="font-bold text-white">{props.node.tagName}</span>
        <span className="text-[#888]">&gt;</span>
      </div>
    </details>
  );
}

/**
 * Render highlighted code while keeping Shiki output responsive in transcripts.
 * Automatically merges externally-provided decorations (e.g. link spans) with
 * any active transcript search highlights from context.
 */
export function HighlightedCode(props: {
  code: string;
  /** Extra Shiki decorations to apply in addition to search highlights. */
  decorations?: DecorationItem[];
  language: BundledLanguage;
}) {
  const search = useTranscriptSearch();
  const searchDecorations = search.active
    ? buildSearchDecorations(props.code, search.normalizedQuery)
    : [];
  const allDecorations = [
    ...(props.decorations ?? []),
    ...searchDecorations,
  ];

  const highlighted = useQuery({
    queryKey: search.active
      ? ["highlight", props.language, props.code, search.normalizedQuery]
      : ["highlight", props.language, props.code],
    queryFn: async (): Promise<ShikiHtml> =>
      (await codeToHtml(props.code, {
        decorations: allDecorations.length ? allDecorations : undefined,
        lang: props.language,
        theme: "github-dark",
      })) as ShikiHtml,
    staleTime: Infinity,
  });

  if (!highlighted.data) {
    return <HighlightedCodeFallback>{props.code}</HighlightedCodeFallback>;
  }

  return <HighlightedCodeHtml html={highlighted.data} />;
}

/** Render unhighlighted code in the same responsive frame as Shiki output. */
export function HighlightedCodeFallback(props: { children: ReactNode }) {
  return (
    <pre className="m-0 min-w-0 whitespace-pre-wrap break-words bg-transparent p-0 font-mono text-[0.86rem] leading-relaxed text-white">
      <code>{props.children}</code>
    </pre>
  );
}

/** Render trusted Shiki HTML with transcript-safe responsive wrapping. */
export function HighlightedCodeHtml(props: { html: ShikiHtml }) {
  return (
    <div
      className="min-w-0 overflow-hidden [&_.line]:block [&_.line]:max-w-full [&_.line]:whitespace-pre-wrap [&_.line]:break-words [&_.line]:[overflow-wrap:anywhere] [&_code]:block [&_code]:max-w-full [&_code]:whitespace-normal [&_code]:break-words [&_code]:[overflow-wrap:anywhere] [&_pre]:!m-0 [&_pre]:!max-w-full [&_pre]:!overflow-hidden [&_pre]:!bg-transparent [&_pre]:!p-0 [&_pre]:whitespace-normal [&_pre]:break-words [&_pre]:font-mono [&_pre]:text-[0.86rem] [&_pre]:leading-relaxed [&_pre]:[overflow-wrap:anywhere] [&_span]:whitespace-pre-wrap [&_span]:break-words [&_span]:[overflow-wrap:anywhere] [&_mark.search-match]:bg-amber-400/20 [&_mark.search-match]:rounded-[2px] [&_mark.search-match]:text-inherit [&_mark.search-match]:not-italic"
      dangerouslySetInnerHTML={{ __html: props.html }}
    />
  );
}
